### PR TITLE
feat: add multiselect intent using Android-ContactPicker

### PR DESCRIPTION
**Pull request by lwhiteley**
added a wrapper for the following library to enable multi-select:
https://github.com/1gravity/Android-ContactPicker

Please see updated AndroidManifest instructions:

https://github.com/lwhiteley/react-native-select-contact-android

There is an issues that is outlined in the Readme

But this is a start. 

Can review/test for now while i keep looking into resolving the issue i mentioned

related to issue #5

### CODE REVIEW

**Comment by rhaker** [comment]
I'd like to hear your thoughts on possibly forking this into an entirely new module where you would be the owner. I'm thinking it could be react-native-select-multiple-contacts-android and then people could choose either case (the single contact vs. multiple contact) and people who just want the single contact wouldn't have to worry about the crashing issue.

The biggest downside of that approach seems to be that the "multiple" contact module still has the single contact inside of it - so there is duplication. It may be that the multiple contact module just eventually kills the single module and everyone just will use one module anyway.

What do you think? Do you think this module is now doing too much and growing too complex? I'm open to what you think since you've done the majority of the recent work.

**Comment by lwhiteley** [comment]
yea i was thinking of splitting it as well due to the issue and the problem it solves

where i created this repo before starting but just decided to use your repo to see what it would look like.

but yea the multi select encompasses the older functionality plus more

https://github.com/lwhiteley/react-native-android-contactpicker

**Comment by rhaker** [comment]
ok. so it probably makes sense to merge the multi select into the android-contactpicker module with you as the owner. I'm going to close the open issue and change the readme to let people know to use the android-contactpicker module if they want a multi select.

**Comment by lwhiteley** [comment]
my repo is updated: https://github.com/lwhiteley/react-native-android-contactpicker

**Pull request closed without merging**
